//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpearHead.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductDetailId { get; set; }
        public System.Guid PacketId { get; set; }
        public System.Guid ProductId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Colur { get; set; }
    
        public virtual Packet Packet { get; set; }
        public virtual Product Product { get; set; }
    }
}
